jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'   # 👈 set a valid version here (3.9 or 3.10 works best)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run audit script
        run: python train_and_audit.py

      - name: Commit artifacts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add audit results"
